FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование кода
COPY . .

# Создание директории для временных файлов
RUN mkdir -p /app/temp_videos

# Запуск бота
CMD ["python", "bot.py"]